services:
  composition_service:
    build:
      context: ./composition
      dockerfile: Dockerfile
    container_name: composition_service
    image: composition_image
    ports:
      - "8082:8082"
    environment:
      - SCORE_SERVICE_HOST=172.19.0.4
      - SCORE_SERVICE_PORT=8081
      - AUTH_SERVICE_HOST=172.19.0.5
      - AUTH_SERVICE_PORT=8080
    env_file:
      - composition/.env
    depends_on:
      - score_service
      - auth_service
    networks:
      app-network:
        ipv4_address: 172.19.0.6

  score_service:
    build:
      context: ./score
      dockerfile: Dockerfile
    container_name: score_service
    image: score_image
    ports:
      - "9091:9091" # gRPC
#      - "8081:8081" # http
    environment:
      - SPRING_DATASOURCE_HOST=172.19.0.2
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres_score
    networks:
      app-network:
        ipv4_address: 172.19.0.4
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -h postgres_score" ]
      interval: 10s
      retries: 5

  auth_service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth_service
    image: auth_image
    ports:
      - "9090:9090" # gRPC
    #      - "8080:8080" # http
    environment:
      - SPRING_DATASOURCE_HOST=172.19.0.3
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres_auth
    networks:
      app-network:
        ipv4_address: 172.19.0.5
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -h postgres_auth" ]
      interval: 10s
      retries: 5

  postgres_score:
    image: postgres:17
    container_name: postgres_score
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: score_db
    volumes:
      - postgres_score_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app-network:
        ipv4_address: 172.19.0.2


  postgres_auth:
    image: postgres:17
    container_name: postgres_auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      app-network:
        ipv4_address: 172.19.0.3

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
  postgres_score_data:
    driver: local
  postgres_auth_data:
    driver: local
